name: Deploy to DeployGate

on:
  pull_request:
    branches:
      - 'develop'
    types: [ closed ]

jobs:
  deploy_to_dp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build APK
        run: ./gradlew assembleDemo

      - name: Distribute App
        run: |
          curl -X POST \
            -sSfL \
            -H "Authorization: token ${{secrets.DEPLOY_GATE_API_KEY}}" \
            -F "message=Build on $(date +'%Y-%m-%d')" \
            -F "distribution_name=android-app-template" \
            -F "file=@app/build/outputs/apk/demo/app-demo.apk" \
            "https://deploygate.com/api/users/${{secrets.DEPLOY_GATE_USER_NAME}}/apps"
